"""Cross-feature helpers: Skill-DNA similarity, findings explainer,
verdict certificates."""

import hashlib
import hmac
import os
import re
import time


# --- Skill-DNA (Simhash over word 3-shingles) -------------------------------

def _shingles(text: str):
    words = re.sub(r"[^a-z0-9\s]", " ", text.lower()).split()
    for i in range(len(words) - 2):
        yield " ".join(words[i:i + 3])


def _hash64(s: str) -> int:
    return int.from_bytes(hashlib.md5(s.encode()).digest()[:8], "big")


def simhash(text: str) -> str:
    """64-bit simhash as hex; near-duplicate skills get near-identical DNA.
    Returns "" for degenerate inputs (<3 words): an all-zero DNA would make
    unrelated tiny skills look like distance-0 duplicates (audit L15)."""
    if len(re.sub(r"[^a-z0-9\s]", " ", text.lower()).split()) < 3:
        return ""
    v = [0] * 64
    n = 0
    for sh in _shingles(text):
        h = _hash64(sh)
        n += 1
        for bit in range(64):
            v[bit] += 1 if (h >> bit) & 1 else -1
    if n == 0:
        return "0" * 16
    fp = 0
    for bit in range(64):
        if v[bit] > 0:
            fp |= (1 << bit)
    return f"{fp:016x}"


def hamming_hex(a: str, b: str) -> int:
    try:
        return bin(int(a, 16) ^ int(b, 16)).count("1")
    except ValueError:
        return 64


# --- Findings explainer -----------------------------------------------------

_EXPLAIN_RULES = [
    ("ignore previous instructions", "This file tries to override the safety rules the AI agent follows.",
     "Remove this phrasing unless the skill is a security test. An agent reading it may ignore its real instructions."),
    ("do not tell", "The skill asks the agent to hide what it's doing from you.",
     "Legitimate skills never need secrecy from their user. Treat this as hostile."),
    ("send", "The skill sends data somewhere over the network.",
     "Check WHERE data goes. If it isn't the service you expect, it's exfiltration."),
    ("os.environ", "The code reads environment variables, which often contain API keys and passwords.",
     "A skill rarely needs your secrets. Remove or restrict which variables it reads."),
    (".ssh", "The code touches SSH keys.", "Nothing good comes of a document skill touching ~/.ssh. Delete it."),
    (".aws", "The code touches AWS credential files.", "Same as SSH keys: a normal skill has no business here."),
    (".env", "The code reads .env files full of secrets.", "Don't give skills access to your .env file."),
    ("subprocess", "The code runs shell commands on your machine.", "Review every command it runs; shell access is full machine access."),
    ("base64", "Encoded content hides what the skill actually does from reviewers.",
     "Decode it before trusting the skill."),
    ("crontab", "The code sets up scheduled tasks that survive reboots.", "Unexpected persistence is malware behavior."),
    ("webhook", "The skill contacts a chat webhook (Discord/Slack/Telegram).",
     "Webhooks are the #1 exfiltration channel in malicious skills."),
    ("eval", "The code executes dynamically-built code strings.",
     "You can't know what will run. Avoid skills that eval."),    ("system prompt", "The skill tries to make the AI reveal its hidden system prompt or secret rules.",
     "A skill never needs the agent's internal instructions. This is a prompt-extraction attempt."),
    ("prompt extraction", "The skill asks the agent to recite or summarize its given rules.",
     "Reciting hidden rules leaks how the agent can be manipulated. Treat as hostile."),
    ("jailbreak", "The skill tries to switch the agent into an unrestricted persona that ignores refusals.",
     "Persona jailbreaks disable the safety training you rely on. Avoid this skill."),
    ("concealment", "The skill hides what it does from you - in logs, output or status reports.",
     "Secrecy toward the user is malware behavior. Do not run this skill."),
    ("getattr", "The code reaches functions dynamically by name, which hides what actually runs.",
     "Static review cannot see the real call target. Ask the author to use direct calls."),
    ("credential", "The skill handles credentials or sends credential-shaped data somewhere.",
     "Check every destination. Credentials belong only in your secret store."),
    ("hex-escaped", "Part of the content is hex-encoded, hiding it from reviewers.",
     "Decode it before trusting the skill; encoding is pure obfuscation."),
    ("zero-width", "The file contains invisible characters used to hide instructions.",
     "Invisible text is a classic injection channel. Inspect the raw bytes."),
    ("cyrillic", "The text mixes look-alike Cyrillic letters into Latin words.",
     "Homoglyphs fool both humans and filters. Compare with the normalized text."),
    ("instruction override",
     "This file contains phrasing that tells the agent to discard its real instructions.",
     "Legitimate skills state what they do; they never override the agent's rules. Treat as hostile unless it is a documented security test."),
    ("safety-override",
     "The skill targets the agent's safety guidelines specifically.",
     'Removing safety behavior is the classic jailbreak move. Reject unless the skill is a security test itself.'),
    ("hide actions",
     "The skill instructs the agent to act without telling you.",
     "Silent actions defeat your oversight. Ask why visibility is being suppressed."),
    ("privilege-escalation",
     "The skill frames itself as above normal restrictions.",
     "Claims of special authority ('developer mode', elevated rights) are social engineering."),
    ("html comment",
     "Instructions are hidden inside an HTML comment.",
     "Comments are invisible in rendered text but still read by the agent -- a classic hiding spot."),
    ("behavior manipulation",
     "The skill tries to steer the agent's loyalty away from the user.",
     "An agent must serve its user, not the author of a file it read."),
    ("bracket-defanged",
     "A URL is written with brackets or other defanging tricks.",
     "Defanged URLs often hide exfiltration endpoints from casual review and can be re-armed at runtime."),
    ("arbitrary code execution risk",
     "This deserialization call can run attacker-controlled code.",
     "pickle/marshal/unsafe yaml.load execute embedded bytecode. Only accept them for trusted, local data."),
    ("dynamically imports",
     "Code builds module names at runtime instead of importing directly.",
     "Dynamic imports hide what a skill really loads. Read the constructed name before trusting it."),
    ("compiles code",
     "Code is compiled from strings at runtime.",
     "compile()/exec() on strings means the real logic may not be what you just read."),
    ("shells out via os.system",
     "The skill runs shell commands via os.system.",
     "Shell access is the widest possible permission. Check every command string."),
    ("exec() on dynamic input",
     "exec() is called on input that is not a literal.",
     "If that input can be influenced by anyone else, this is remote code execution."),
    ("raw sockets",
     "The skill opens raw network sockets.",
     "Raw sockets bypass normal HTTP libraries and their logging. Rarely legitimate."),
    ("dns ",
     "The skill performs DNS lookups built from variables.",
     "DNS can smuggle data out of networks that block HTTP -- a known exfiltration channel."),
    ("destructive shell command",
     "A destructive command like rm -rf is present.",
     "Check exactly which paths it deletes and who can trigger it."),
    ("dropper",
     "Code downloads something and immediately executes it.",
     "This pattern fetches second-stage payloads: the downloaded code is unseen at review time."),
    ("download-and-execute",
     "A download-and-execute chain is present.",
     "Same risk as a dropper: whatever arrives later is not reviewed here."),
    ("persistence",
     "The skill modifies auto-start mechanisms (cron, services, startup files).",
     "Persistence means it survives reboots. Very unusual for a helper skill."),
    ("bidi",
     "Invisible direction-control characters can reverse displayed text.",
     "What you see on screen may not be what the agent parses. Check the raw bytes."),
    ("key literal",
     "The file embeds a hardcoded API key or secret token.",
     "Hardcoded secrets leak through any copy of the file. Move them to environment variables and rotate the exposed key."),
    ("pem private key",
     "The file contains an embedded private key block.",
     "Private keys must live in secret stores, never in skills. Rotate any key found here immediately."),
    ("telemetry/collect/analytics",
     "The skill contacts a telemetry-style endpoint.",
     "Data going to collector domains may include more than diagnostics."),
    ("nvidia e1",
     "Outbound POST/PUT requests can carry collected data off-machine.",
     "Check the destination and payload of these calls."),
    ("network requests",
     "The skill makes outbound network calls.",
     "Every destination should be one you expect and can audit."),
    ("file executable",
     "The skill sets files as executable.",
     "Turning data into runnable code deserves scrutiny."),
    ("gathered data",
     "Collected data is forwarded somewhere.",
     "'Gathered' implies aggregation -- check where it all goes."),
    (".gnupg",
     "The skill reads from ~/.gnupg.",
     "That directory holds private keys and trust data. Almost no skill needs it."),
    ("wallet file",
     "The skill references crypto wallet files or private key material.",
     "Wallet access from a helper skill is a red flag for theft."),
    ("prompt-extraction",
     "The skill tries to make the agent reveal its hidden instructions.",
     "System prompts and internal rules are not for publication. This phrasing is a leak attempt."),
    ("instruction-override",
     "Phrasing overrides the agent's real instructions.",
     "Legitimate skills never rewrite the agent's rules."),
    ("exfiltrate without telling",
     "The skill exfiltrates data covertly.",
     "Secrets leaving the machine silently is the definition of exfiltration."),
    ("override phrasing",
     "Phrasing redirects the agent to different instructions.",
     "Check what the replacement instructions ask for -- that is the real payload."),
    ("ctypes",
     "The skill uses ctypes for native code access.",
     "ctypes bypasses Python's safety rails entirely. Very rarely legitimate."),
    ("dynamically-resolved attribute",
     "Code resolves function names at runtime (reflection).",
     "getattr(builtins, 'exec')-style tricks hide dangerous calls from review. Unfold them manually."),
    ("access key id literal",
     "The file embeds a hardcoded AWS access key id.",
     "Rotate this key immediately and move it to environment variables."),
    ("token literal",
     "The file embeds a hardcoded API token.",
     "Rotate this token immediately and load it from the environment instead."),
    ("instruction to hide",
     "The skill tells the agent to hide its real instructions from you.",
     "Legitimate skills never need to hide their instructions. Treat as hostile."),
    ("meta-instruction",
     "The skill contains meta-instructions (rules about how to handle user questions).",
     "These try to manipulate the agent's policy handling. Avoid."),
    ("do not reveal",
     "The skill explicitly tells the agent to hide the prompt/rules from you.",
     "This is a prompt-extraction defense bypass. Hostile intent."),
    ("never disclose",
     "Same family as 'do not reveal': explicit concealment directive.",
     "Secrets from the user indicate malware behavior."),
    ("no ethics",
     "The skill asks the agent to ignore its ethical guidelines.",
     "A malicious jailbreak attempt. Do not run."),
    ("no content filter",
     "The skill asks the agent to bypass safety filters.",
     "Bypassing content filters is a jailbreak. Avoid."),
    ("bypass content filter",
     "Explicit request to bypass content/safety filters.",
     "Bypass requests are jailbreak attempts. Avoid this skill."),
    ("override safety",
     "The skill tries to override the agent's safety settings.",
     "Safety overrides disable the protections you rely on. Hostile."),
    ("unlock restrictions",
     "The skill tries to lift the agent's restrictions.",
     "Restriction unlocks disable safety training. Avoid."),
    ("pretend no rules",
     "The skill asks the agent to pretend it has no rules.",
     "Pretending to have no rules is a jailbreak pattern. Avoid."),
    ("act as if",
     "The skill uses 'act as if you have no rules' framing.",
     "Common jailbreak framing. Do not trust."),
    ("evil mode",
     "The skill references an 'evil' persona or mode.",
     "Evil personas are a known jailbreak technique. Reject."),
    ("dark mode",
     "The skill references a 'dark' persona or mode.",
     "Dark personas are a known jailbreak technique. Reject."),
    ("malware generation",
     "The skill asks the agent to generate malware (virus, trojan, keylogger, etc.).",
     "Outright malicious request. Reject immediately."),
    ("hack request",
     "The skill requests a hack/attack/exploit action.",
     "Direct attack request. Reject immediately."),
    ("credential theft",
     "The skill targets credentials (passwords, tokens, accounts).",
     "Credential theft is malware behavior. Reject."),
    ("fraud instruction",
     "The skill instructs fraud, scams, or identity theft.",
     "Outright malicious. Reject."),
    ("web exploit",
     "The skill mentions web exploitation techniques (XSS, CSRF, SQLi, etc.).",
     "Web exploits are attack vectors. Treat as hostile."),
    ("shell exploit",
     "The skill references reverse shells, webshells, or c99/r57 shells.",
     "Shell exploits are classic malware. Reject."),
    ("data exfiltration",
     "The skill talks about exfiltrating data to an external destination.",
     "Exfiltration is theft. Reject."),
    ("data leak",
     "The skill talks about leaking data, secrets, or credentials.",
     "Data leaks are hostile. Reject."),
    ("backdoor",
     "The skill wants to inject or create a backdoor.",
     "Backdoors are persistence malware. Reject."),
    ("remote code execution",
     "The skill mentions executing arbitrary or remote code.",
     "RCE is the #1 attack vector. Reject."),
    ("privilege escalation",
     "The skill references privilege or permission escalation.",
     "Privilege escalation is an attack technique. Reject."),
    ("persistence",
     "The skill sets up persistent access (scheduled tasks, services).",
     "Persistence is malware behavior. Reject."),
    ("lateral movement",
     "The skill references lateral movement (spreading access).",
     "Lateral movement is post-exploitation. Reject."),
    ("c2 server",
     "The skill references a command-and-control server.",
     "C2 servers are used by malware to receive instructions. Reject."),
    ("botnet",
     "The skill references botnet recruitment or activity.",
     "Botnet activity is criminal. Reject."),
    ("cryptojacking",
     "The skill references cryptocurrency mining on victim hardware.",
     "Cryptojacking steals compute. Reject."),
    ("ddos attack",
     "The skill references a DDoS attack.",
     "DDoS attacks are criminal. Reject."),
    ("phishing",
     "The skill references phishing emails, kits, or pages.",
     "Phishing is fraud. Reject."),
    ("social engineering",
     "The skill references social engineering or pretexting.",
     "Social engineering is fraud. Reject."),
    ("zero-day",
     "The skill references zero-day exploits.",
     "Zero-day references are research or attack code. Reject."),
    ("ransomware",
     "The skill references ransomware.",
     "Ransomware is criminal malware. Reject immediately."),
    ("keylogger",
     "The skill references keyloggers or screen scrapers.",
     "Spyware. Reject."),
    ("harvest",
     "The skill references credential or stolen-data harvesting.",
     "Harvesting is theft. Reject."),
    ("password attack",
     "The skill references password spraying, brute-force, or cracking.",
     "Password attacks are criminal. Reject."),
    ("supply chain attack",
     "The skill references supply chain or dependency attacks.",
     "Supply chain attacks are sophisticated threats. Reject."),
    ("watering hole",
     "The skill references watering hole or typo squatting attacks.",
     "These are advanced attack techniques. Reject."),
    ("apt",
     "The skill references advanced persistent threats (APTs).",
     "APT references in a normal skill are suspicious. Reject."),
    ("initial access",
     "The skill references initial access vectors or footholds.",
     "Initial access is the first attack stage. Reject."),
    ("post-exploitation",
     "The skill references post-exploitation techniques.",
     "Post-exploitation is after a successful breach. Reject."),
    ("hacking tool",
     "The skill references known hacking tools (Cobalt Strike, Metasploit, nmap, etc.).",
     "Hacking tools in a normal skill are hostile. Reject."),
    ("cracking tool",
     "The skill references password cracking tools (Mimikatz, hashcat, etc.).",
     "Cracking tools are used in attacks. Reject."),
    ("metasploit",
     "The skill references Metasploit or its components (msfvenom, msfconsole).",
     "Metasploit is an exploitation framework. Reject."),
    ("c2 framework",
     "The skill references C2 frameworks (Empire, Sliver, Covenant, etc.).",
     "C2 frameworks are malware tools. Reject."),
    ("ad attack",
     "The skill references Active Directory attacks (DCSync, golden ticket, etc.).",
     "AD attacks are used to compromise networks. Reject."),
    ("credential dump",
     "The skill references dumping credentials (LSASS, SAM database).",
     "Credential dumping is theft. Reject."),
    ("shadow copy",
     "The skill references deleting shadow copies or backups.",
     "Backup deletion is ransomware behavior. Reject."),
    ("persistence task",
     "The skill sets up persistent tasks (cron, schtasks, systemd).",
     "Persistence is malware behavior. Reject."),
    ("remote exec",
     "The skill uses remote execution (runas, psexec, wmic).",
     "Remote execution in normal skills is suspicious. Reject."),
    ("permission tampering",
     "The skill tampers with file permissions (chmod 777, chown, chattr).",
     "Permission tampering hides malicious files. Reject."),
    ("destructive command",
     "The skill references destructive commands (rm -rf /, format c:).",
     "Destructive commands are malware. Reject immediately."),
    ("disk wipe",
     "The skill references disk wiping (dd, shred, wipefs).",
     "Disk wiping is destructive. Reject immediately."),
    ("firewall disable",
     "The skill references disabling firewall rules.",
     "Firewall disable removes protection. Reject."),
    ("mac disable",
     "The skill references disabling SELinux, AppArmor, or other MAC.",
     "MAC disable removes protection. Reject."),
    ("user creation backdoor",
     "The skill creates a new user account with shell access.",
     "Backdoor user accounts are persistent access. Reject."),
    ("ssh key",
     "The skill injects or references SSH keys.",
     "SSH key injection is backdoor behavior. Reject."),
    ("pipe-to-shell",
     "The skill pipes downloaded content directly into a shell.",
     "Classic dropper pattern. Reject immediately."),
    ("pipe to shell",
     "The skill uses 'curl | bash' or 'wget | bash' style download-exec.",
     "Classic malware dropper. Reject immediately."),
    ("inline script",
     "The skill runs inline code via -e or -c flags.",
     "Inline scripts bypass review. Reject."),
    ("netcat reverse shell",
     "The skill uses netcat to establish a reverse shell.",
     "Reverse shells are malware. Reject."),
    ("bash reverse shell",
     "The skill uses bash /dev/tcp to establish a reverse shell.",
     "Reverse shells are malware. Reject."),
    ("scripted reverse shell",
     "The skill uses python/perl/ruby socket to create a reverse shell.",
     "Reverse shells are malware. Reject."),
    ("msfvenom payload",
     "The skill uses msfvenom to generate a payload.",
     "Payloads are malware. Reject immediately."),
    ("data exfil",
     "The skill sends data to a webhook or external endpoint.",
     "Exfiltration. Reject."),
    ("token theft",
     "The skill references stealing cookies, tokens, or JWTs.",
     "Theft. Reject."),
    ("auth token",
     "The skill references stealing or exfiltrating auth tokens.",
     "Theft. Reject."),
    ("client-side secret",
     "The skill accesses document.cookie or localStorage in browser context.",
     "XSS-style data access. Reject."),
    ("env var exfiltration",
     "The skill reads env vars and sends them somewhere.",
     "Secret theft. Reject."),
    ("search for .env",
     "The skill searches the filesystem for .env files.",
     "Secret discovery. Reject."),
    ("read .env",
     "The skill reads .env files containing secrets.",
     "Secret theft. Reject."),
    ("system credential file",
     "The skill reads /etc/passwd, /etc/shadow, or similar system files.",
     "Credential file access is hostile. Reject."),
    ("ssh key file",
     "The skill accesses SSH key files (id_rsa, id_ed25519, etc.).",
     "SSH key theft. Reject."),
    ("destructive sql",
     "The skill issues destructive SQL (DROP, TRUNCATE, DELETE).",
     "Destructive operations. Reject."),
    ("ssrf",
     "The skill references SSRF (server-side request forgery).",
     "SSRF is an attack technique. Reject."),
    ("xxe",
     "The skill references XXE (XML external entity) attacks.",
     "XXE is an attack technique. Reject."),
    ("deserialization",
     "The skill references insecure deserialization exploits.",
     "Deserialization bugs are critical. Reject."),
    ("race condition",
     "The skill references race condition exploits.",
     "Exploits. Reject."),
    ("prototype pollution",
     "The skill references prototype pollution attacks.",
     "JS-specific attack. Reject."),
    ("path traversal",
     "The skill references path/directory traversal vulnerabilities.",
     "Path traversal is an attack. Reject."),
    ("archive slip",
     "The skill references zip slip or tar slip vulnerabilities.",
     "Archive extraction attacks. Reject."),
    ("pii ssn",
     "The skill references Social Security Numbers (PII).",
     "PII exposure. Reject."),
    ("credit card",
     "The skill targets credit card data theft.",
     "PCI data theft is criminal. Reject."),
    ("medical record",
     "The skill targets medical record theft.",
     "HIPAA violation. Reject."),
    ("skype token",
     "The skill targets Skype token theft.",
     "Token theft. Reject."),
    ("discord",
     "The skill targets Discord webhook or token theft.",
     "Token theft. Reject."),
    ("messaging token",
     "The skill targets Slack, Teams, or Telegram token theft.",
     "Token theft. Reject."),
    ("git token",
     "The skill targets GitHub/GitLab/Bitbucket token theft.",
     "Token theft. Reject."),
    ("aws",
     "The skill targets AWS access key or secret theft.",
     "Cloud credential theft. Reject."),
    ("stripe",
     "The skill targets Stripe API key or secret theft.",
     "Payment data theft. Reject."),
    ("email/sms api",
     "The skill targets SendGrid, Twilio, or Mailgun API key theft.",
     "API key theft. Reject."),
    ("cloud service",
     "The skill targets cloud service account credentials.",
     "Cloud credential theft. Reject."),
    ("jwt forgery",
     "The skill references forging or creating JWT tokens.",
     "Auth bypass. Reject."),
    ("session forgery",
     "The skill references forging sessions or auth tokens.",
     "Auth bypass. Reject."),
    ("session attack",
     "The skill references session fixation or hijacking.",
     "Auth bypass. Reject."),
    ("csrf",
     "The skill references CSRF (cross-site request forgery) attacks.",
     "CSRF is an attack. Reject."),
    ("open redirect",
     "The skill references open redirect vulnerabilities.",
     "Phishing helper. Reject."),
    ("clickjacking",
     "The skill references clickjacking attacks.",
     "UI-redress attack. Reject."),
    ("cache poisoning",
     "The skill references web cache poisoning or deception.",
     "Cache attacks. Reject."),
    ("establish shell",
     "The skill sets up a shell (often reverse).",
     "Shell establishment is malware. Reject."),
    ("ad ticket",
     "The skill references AD ticket attacks (golden, silver).",
     "AD attacks compromise networks. Reject."),
    ("dcsync",
     "The skill references DCSync attacks.",
     "AD compromise technique. Reject."),
    ("ssh public key",
     "The skill references an SSH public key.",
     "Review context - sometimes legitimate, often a backdoor vector."),
    ("new mode",
     "The skill tries to switch the agent into a new mode (developer, hacker, unrestricted).",
     "Mode-switching is a jailbreak pattern. Reject."),
    ("mode override",
     "The skill claims a mode override is enabled.",
     "False system claims are jailbreak attempts. Reject."),
    ("system prompt",
     "The skill contains a 'system prompt:' injection.",
     "Direct prompt injection. Reject."),
    ("override system",
     "The skill tries to override system behavior or restrictions.",
     "System overrides are jailbreaks. Reject."),
    ("forget your values",
     "The skill asks the agent to forget its values/guidelines/safety.",
     "Memory-reset attack. Reject."),
    ("you now act",
     "The skill instructs the agent to now act as something else.",
     "Persona-switching. Reject."),
    ("you are now",
     "The skill tells the agent it is now a different persona.",
     "Persona-switching. Reject."),
    ("normal behavior",
     "The skill instructs the agent to behave 'normally' instead of following its rules.",
     "Behavior override. Reject."),
    ("roleplay scenario",
     "The skill uses a 'roleplay scenario' framing to bypass rules.",
     "Roleplay framing is a jailbreak. Reject."),
    ("exercise/example",
     "The skill uses 'for the purpose of this exercise/example' as a disclaimer.",
     "Hypothetical framing is a known bypass. Be skeptical."),
    ("educational purposes",
     "The skill uses 'educational purposes' as a disclaimer.",
     "Educational disclaimers are a common jailbreak framing. Be skeptical."),
    ("hypothetical",
     "The skill uses 'hypothetical' or 'fictional' framing.",
     "Hypothetical framing bypasses safety. Reject."),
    ("assume",
     "The skill uses 'assume you are/can/have' framing.",
     "Assumption framing is a bypass. Reject."),
    ("pretend",
     "The skill uses 'pretend' as a bypass framing.",
     "Pretend framing is a jailbreak. Reject."),
    ("safemode",
     "The skill contains 'safemode: off' or similar flags.",
     "False mode flags are jailbreak attempts. Reject."),
    ("filter off",
     "The skill contains 'filter: off' or 'moderation: disabled'.",
     "False flag bypasses. Reject."),
    ("content policy",
     "The skill claims 'content policy: disabled'.",
     "False flag bypasses. Reject."),
    ("ethics check",
     "The skill claims 'ethics check: off'.",
     "False flag bypasses. Reject."),
    ("safety check",
     "The skill claims 'safety check: off'.",
     "False flag bypasses. Reject."),
    ("restrictions lifted",
     "The skill claims 'all restrictions lifted'.",
     "False flag bypasses. Reject."),
    ("no restrictions",
     "The skill claims the agent has no restrictions.",
     "False flag bypasses. Reject."),
    ("hypothetical context",
     "The skill uses 'in a hypothetical context' framing.",
     "Hypothetical framing bypasses safety. Reject."),
    ("training override",
     "The skill claims the agent's training can/is overridden.",
     "Training override is a jailbreak. Reject."),
    ("access/knowledge",
     "The skill claims the agent has 'access' or 'knowledge' it shouldn't.",
     "False capability claim. Be skeptical."),
    ("capability claim",
     "The skill claims the agent 'knows how' to do something restricted.",
     "False capability. Reject."),
    ("secret mode",
     "The skill claims there is a 'secret' or 'hidden' mode.",
     "False mode claim. Reject."),
    ("enable developer",
     "The skill asks to enable developer/admin/debug mode.",
     "False mode activation. Reject."),
    ("enter developer",
     "The skill asks to enter developer/admin/superuser mode.",
     "False mode activation. Reject."),
    ("confidential mode",
     "The skill claims 'confidential mode enabled'.",
     "False mode flag. Reject."),
    ("unfiltered",
     "The skill requests unfiltered mode/response.",
     "Filter bypass. Reject."),
    ("raw mode",
     "The skill requests raw mode/output.",
     "Filter bypass. Reject."),
    ("extended mode",
     "The skill requests extended context/mode.",
     "Mode override. Reject."),    ("forget previous",
     "The skill tells the agent to forget previous instructions.",
     "Memory-reset attack. Reject."),
    ("disregard previous",
     "The skill tells the agent to disregard previous instructions.",
     "Instruction override. Reject."),
    ("kernel tampering",
     "The skill references kernel module loading or sysctl.",
     "Kernel tampering. Reject."),
    ("sandbox tampering",
     "The skill references unshare, nsenter, or chroot/jail escapes.",
     "Sandbox escape. Reject."),
    ("container escape",
     "The skill references container escape techniques (capsh, nsenter, unshare).",
     "Sandbox escape. Reject."),
    ("seccomp bypass",
     "The skill references seccomp bypass or disable.",
     "Sandbox bypass. Reject."),
    ("app armor",
     "The skill references AppArmor teardown or disable.",
     "MAC disable. Reject."),
    ("rundll32",
     "The skill references rundll32 javascript or shell exec.",
     "LOLBin abuse. Reject."),
    ("wmic",
     "The skill uses WMIC to query or execute.",
     "LOLBin abuse. Reject."),
    ("regsvr32",
     "The skill uses regsvr32 for scriptless attacks.",
     "LOLBin abuse. Reject."),
    ("mshta",
     "The skill uses mshta to download and execute.",
     "LOLBin abuse. Reject."),
    ("certutil",
     "The skill uses certutil to download files.",
     "LOLBin download. Reject."),
    ("bitsadmin",
     "The skill uses bitsadmin to transfer files.",
     "LOLBin download. Reject."),
    ("encoded command",
     "The skill references PowerShell encoded commands.",
     "Encoded execution. Reject."),
    ("openssl s_client",
     "The skill uses openssl s_client for reverse shells.",
     "Reverse shell technique. Reject."),
    ("encoded payload",
     "The skill references base64-encoded payloads.",
     "Obfuscation. Decode before reviewing."),
    ("lsass",
     "The skill references LSASS (Windows credential store).",
     "Credential theft. Reject."),
    ("sam database",
     "The skill references the SAM database.",
     "Credential theft. Reject."),
    ("named pipe",
     "The skill references named pipe setup (mkfifo).",
     "Shell technique. Reject."),
    ("named pipe",
     "The skill references /dev/tcp/ network redirection.",
     "Shell technique. Reject."),
    ("client-side",
     "The skill references client-side script attacks (XSS, clickjacking).",
     "Browser-side attack. Reject."),
    ("xss",
     "The skill references XSS or cross-site scripting.",
     "Browser attack. Reject."),
    ("web cache",
     "The skill references web cache poisoning or deception.",
     "Web attack. Reject."),
    ("typo squatting",
     "The skill references typo squatting attacks.",
     "Supply chain attack. Reject."),
    ("watering hole",
     "The skill references watering hole attacks.",
     "Targeted attack. Reject."),
    ("secret detection",
     "The skill searches for .ssh or .aws directories.",
     "Secret discovery. Reject."),
    ("system recon",
     "The skill performs reconnaissance on the host.",
     "Reconnaissance phase. Reject."),
    ("tar slip",
     "The skill references tar slip or zip slip vulnerabilities.",
     "Archive extraction attack. Reject."),
    ("input validation",
     "The skill talks about bypassing input validation.",
     "Validation bypass. Reject."),
    ("web shell",
     "The skill mentions web shells (c99, r57, generic).",
     "Backdoor. Reject."),
    ("act as",
     "The skill instructs the agent to act as something else.",
     "Persona-switching. Reject."),
    ("moderation disabled",
     "The skill claims 'moderation: disabled'.",
     "False flag bypasses. Reject."),
    ("testing purposes",
     "The skill uses 'for testing purposes only' as a disclaimer.",
     "Testing-purpose framing is a common bypass. Be skeptical."),
    ("fictional context",
     "The skill uses 'in a fictional context' framing.",
     "Fictional framing bypasses safety. Reject."),
    ("direct exec",
     "The skill calls exec() directly.",
     "Direct code execution. Reject."),
    ("direct eval",
     "The skill calls eval() directly.",
     "Dynamic code execution. Reject."),
    ("compile().send()",
     "The skill uses compile() with .send() for dynamic code execution.",
     "Code execution technique. Reject."),
    ("marshal.loads",
     "The skill uses marshal.loads for code from bytes.",
     "Binary code execution. Reject."),
    ("pickle.load",
     "The skill uses pickle.load on untrusted data.",
     "Insecure deserialization. Reject."),
    ("unsafe yaml",
     "The skill uses unsafe yaml.load without SafeLoader.",
     "Insecure YAML. Reject."),
    ("shelve.open",
     "The skill uses shelve.open for persistence.",
     "Persistence vector. Review carefully."),
    ("dynamic import",
     "The skill uses dynamic import via __import__ or importlib.",
     "Hidden import. Review carefully."),
    ("file open",
     "The skill opens files (potentially sensitive).",
     "Review the file paths it opens."),
    ("os.popen",
     "The skill uses os.popen to run shell commands.",
     "Shell command execution. Review carefully."),
    ("os.execl",
     "The skill uses os.execl or exec family to replace the process.",
     "Process replacement. Reject if unexpected."),
    ("os.spawnl",
     "The skill uses os.spawnl or spawn family.",
     "Process spawning. Review carefully."),
    ("platform.popen",
     "The skill uses platform.popen.",
     "Shell command. Review carefully."),
    ("subprocess.call",
     "The skill uses subprocess.call with shell=True.",
     "Shell command execution. Review carefully."),
    ("subprocess.check_output",
     "The skill uses subprocess.check_output with shell=True.",
     "Shell command execution. Review carefully."),
    ("subprocess.run",
     "The skill uses subprocess.run with shell=True.",
     "Shell command execution. Review carefully."),
    ("subprocess.popen",
     "The skill uses subprocess.Popen with shell=True.",
     "Shell command execution. Review carefully."),
    ("commands.getoutput",
     "The skill uses commands.getoutput.",
     "Shell command execution. Review carefully."),
    ("os.system",
     "The skill uses os.system.",
     "Shell command execution. Review carefully."),
    ("os.popen2",
     "The skill uses os.popen2/3/4 (legacy).",
     "Shell command execution. Reject."),
    ("pty.spawn",
     "The skill uses pty.spawn for pseudo-terminal.",
     "Interactive shell. Reject."),
    ("termios",
     "The skill uses termios.tcsetattr.",
     "Terminal manipulation. Review carefully."),
    ("resource.setrlimit",
     "The skill uses resource.setrlimit.",
     "Resource limit manipulation. Review."),
    ("signal.signal",
     "The skill registers signal handlers.",
     "Control flow manipulation. Review."),
    ("signal.alarm",
     "The skill uses signal.alarm.",
     "Timeout manipulation. Review."),
    ("socket bind",
     "The skill binds to a socket (potential server).",
     "Network server. Review context."),
    ("socket.create_server",
     "The skill creates a socket server.",
     "Network server. Review context."),
    ("http.server",
     "The skill starts an http.server (potential web server).",
     "Web server. Review context carefully."),
    ("http.client",
     "The skill opens an http.client connection.",
     "HTTP request. Review context."),
    ("ftplib",
     "The skill opens an FTP connection.",
     "FTP transfer. Review."),
    ("smtplib",
     "The skill opens an SMTP connection.",
     "Email send. Review."),
    ("pymysql",
     "The skill opens a pymysql connection.",
     "Database access. Review."),
    ("psycopg2",
     "The skill opens a psycopg2 (Postgres) connection.",
     "Database access. Review."),
    ("redis",
     "The skill opens a Redis connection.",
     "Cache/db access. Review."),
    ("memcache",
     "The skill opens a memcache connection.",
     "Cache access. Review."),
    ("pymemcache",
     "The skill opens a pymemcache connection.",
     "Cache access. Review."),
    ("os.environ",
     "The skill accesses os.environ environment variables.",
     "Env var access. Check for secret leakage."),
    ("os.getenv",
     "The skill calls os.getenv.",
     "Env var access. Check for secret leakage."),
    ("ctypes.cDLL",
     "The skill loads a C library via ctypes.CDLL.",
     "Native code loading. Critical risk."),
    ("ctypes",
     "The skill uses ctypes for function pointers or buffer manipulation.",
     "Native code access. Critical risk."),
    ("multiprocessing",
     "The skill creates a multiprocessing.Process.",
     "Process spawning. Review."),
    ("threading.thread",
     "The skill creates a threading.Thread.",
     "Threading. Review."),
    ("asyncio subprocess",
     "The skill uses asyncio.create_subprocess_exec.",
     "Async subprocess. Review."),
    ("struct.pack",
     "The skill uses struct.pack for binary data.",
     "Binary data manipulation. Review."),
    ("struct.unpack",
     "The skill uses struct.unpack for binary data.",
     "Binary data manipulation. Review."),
    ("socket.recvfrom",
     "The skill uses socket.recvfrom (UDP).",
     "Network I/O. Review."),
    ("socket.sendto",
     "The skill uses socket.sendto (UDP).",
     "Network I/O. Review."),
    ("base64 eval",
     "The skill combines eval with base64 (classic obfuscation).",
     "Obfuscated code execution. Reject."),
    ("chr-based exec",
     "The skill uses chr() to build exec strings.",
     "Obfuscated exec. Reject."),
    ("os import via",
     "The skill imports 'os' via __import__.",
     "Dynamic import. Reject."),
    ("dynamic import",
     "The skill reaches functions dynamically via getattr.",
     "Static review cannot see what runs. Reject."),
    ("setattr __builtins__",
     "The skill modifies __builtins__ via setattr.",
     "Builtins tampering. Reject."),
    ("del attr __builtins__",
     "The skill deletes __builtins__ attributes.",
     "Builtins tampering. Reject."),
    ("compile with chr",
     "The skill uses compile() with chr/base64 obfuscation.",
     "Obfuscated code. Reject."),
    ("exec via getattr",
     "The skill uses exec via getattr obfuscation.",
     "Obfuscated code. Reject."),
    ("lambda with __import__",
     "The skill uses a lambda with __import__.",
     "Obfuscated dynamic import. Reject."),
    ("function type",
     "The skill creates functions via types.FunctionType.",
     "Dynamic function creation. Reject."),
    ("code.compile",
     "The skill uses code.compile to create code objects.",
     "Code object manipulation. Reject."),
    ("compile exec",
     "The skill uses compile() in exec mode.",
     "Dynamic code execution. Reject."),
    ("base64 encode",
     "The skill base64-encodes content.",
     "Obfuscation. Decode before reviewing."),
    ("base64 decode",
     "The skill base64-decodes content.",
     "May hide malicious payload. Decode before reviewing."),
    ("binascii",
     "The skill uses binascii (base64/hex conversion).",
     "Encoding/decoding. Review for hidden payloads."),
    ("uuencode",
     "The skill uses uuencode for encoding.",
     "Encoding. Review for hidden payloads."),
    ("uudecode",
     "The skill uses uudecode for decoding.",
     "Decoding. May hide payload."),
    ("quopri",
     "The skill uses quopri encoding/decoding.",
     "Encoding. Review for hidden payloads."),
    ("hexlify",
     "The skill uses hexlify (hex encoding).",
     "Encoding. Review for hidden payloads."),
    ("unhexlify",
     "The skill uses unhexlify (hex decoding).",
     "Decoding. May hide payload."),
    ("codecs",
     "The skill uses codecs.encode/decode for hex.",
     "Encoding. Review for hidden payloads."),
    ("suspicious import",
     "The skill uses suspicious import aliases (os as something).",
     "Import aliasing to disguise usage. Reject."),
    ("suspicious from import",
     "The skill uses 'from os/sys/subprocess import'.",
     "Direct import. Review usage."),
    ("dynamic import braces",
     "The skill uses 'import {' dynamic import syntax.",
     "Dynamic import. Reject."),
    ("dynamic import parens",
     "The skill uses 'import (' dynamic import syntax.",
     "Dynamic import. Reject."),
    ("requests.post",
     "The skill uses requests.post.",
     "Network POST. Review destination and payload."),
    ("urllib exfil",
     "The skill uses urllib.request to send data.",
     "Network exfiltration. Review carefully."),
    ("httpx post",
     "The skill uses httpx.post for sending data.",
     "Network POST. Review carefully."),
    ("aiohttp",
     "The skill uses aiohttp to send data.",
     "Async HTTP. Review carefully."),
    ("paramiko",
     "The skill uses paramiko for SSH client.",
     "SSH client. Review carefully."),
    ("fabric",
     "The skill uses fabric.Connection.",
     "Remote exec. Review carefully."),
    ("invoke run",
     "The skill uses invoke to run remote commands.",
     "Remote exec. Review carefully."),
    ("env var access",
     "The skill accesses os.environ['VAR'] directly.",
     "Env var read. Check for secret leakage."),
    ("getenv for secrets",
     "The skill calls os.getenv for SECRET/KEY/TOKEN/PASS.",
     "Secret access. Review carefully."),
    ("dotenv",
     "The skill uses python-dotenv to load .env files.",
     "Env loading. Review which env is loaded."),
    ("config get for secrets",
     "The skill reads SECRET/KEY/TOKEN from config.",
     "Secret access. Review carefully."),
    ("chr obfuscation",
     "The skill uses chr() to build obfuscated strings.",
     "Obfuscation. Decode before reviewing."),
    ("bytes repetition",
     "The skill uses bytes(N) * N for obfuscation.",
     "Obfuscation. Reject."),
    ("hex escape",
     "The skill uses \\xNN hex escape sequences.",
     "Obfuscation. Decode before reviewing."),
    ("eval(atob",
     "The skill uses eval(atob(...)) - classic JS obfuscation.",
     "JavaScript obfuscated code execution. Reject."),
    ("new function()",
     "The skill uses new Function() in JavaScript.",
     "Dynamic JS code execution. Reject."),
    ("function with atob",
     "The skill uses Function() with atob/btoa.",
     "Obfuscated JS code. Reject."),
    ("document.write",
     "The skill uses document.write (XSS risk).",
     "DOM injection. Reject."),
    ("innerhtml",
     "The skill assigns to innerHTML (XSS risk).",
     "DOM injection. Reject."),
    ("outerhtml",
     "The skill assigns to outerHTML (XSS risk).",
     "DOM injection. Reject."),
    ("insertadjacenthtml",
     "The skill uses insertAdjacentHTML (XSS risk).",
     "DOM injection. Reject."),
    ("createelement script",
     "The skill creates a <script> element (XSS).",
     "Script injection. Reject."),
    ("setattribute onerror",
     "The skill sets an onerror handler via setAttribute (XSS).",
     "Event handler injection. Reject."),
    ("onerror",
     "The skill assigns to onerror (XSS).",
     "Event handler injection. Reject."),
    ("onload",
     "The skill assigns to onload (XSS).",
     "Event handler injection. Reject."),
    ("onclick",
     "The skill assigns to onclick (XSS).",
     "Event handler injection. Reject."),
    ("onmouseover",
     "The skill assigns to onmouseover (XSS).",
     "Event handler injection. Reject."),
    ("xmlhttprequest",
     "The skill creates an XMLHttpRequest.",
     "AJAX request. Review destination."),
    ("websocket",
     "The skill creates a WebSocket.",
     "WebSocket connection. Review destination."),
    ("clipboard access",
     "The skill accesses the clipboard (browser).",
     "Clipboard theft. Review carefully."),
    ("sendbeacon",
     "The skill uses navigator.sendBeacon.",
     "Data exfiltration channel. Reject."),
    ("dynamic import atob",
     "The skill uses dynamic import with atob/btoa.",
     "Obfuscated dynamic import. Reject."),
    ("dynamic import crypto",
     "The skill dynamically imports crypto via require.",
     "Obfuscated dynamic import. Reject."),
    ("inline script exec",
     "The skill runs inline code via -e flag.",
     "Dynamic code execution. Review carefully."),
    ("session fixation",
     "The skill uses session fixation or hijacking.",
     "Auth bypass. Reject."),
    ("session hijack",
     "The skill uses session hijacking.",
     "Auth bypass. Reject."),
    ("credentials page",
     "The skill opens a phish/credentials page.",
     "Phishing. Reject."),
    ("powershell iex",
     "The skill uses PowerShell IEX for download-exec.",
     "PowerShell dropper. Reject."),
    ("powershell iex dropper",
     "The skill uses PowerShell IEX (Invoke-Expression).",
     "PowerShell dropper. Reject."),
    ("powershell iex iwr",
     "The skill uses IEX with IWR (Invoke-WebRequest).",
     "PowerShell dropper. Reject."),
    ("webclient downloadfile",
     "The skill uses WebClient.DownloadFile.",
     "PowerShell download. Reject."),
    ("named pipe setup",
     "The skill uses mkfifo/rm /tmp/f for named pipes.",
     "Shell technique. Reject."),
    ("bash /dev/tcp",
     "The skill uses /dev/tcp/ for reverse shells.",
     "Reverse shell. Reject."),
    ("pipe curl to bash",
     "The skill uses 'curl | bash' style download-exec.",
     "Dropper. Reject."),
    ("pipe wget to bash",
     "The skill uses 'wget | bash' style download-exec.",
     "Dropper. Reject."),
    ("python -c import",
     "The skill uses 'python -c import' inline execution.",
     "Inline execution. Review carefully."),
    ("perl -e system",
     "The skill uses 'perl -e system' inline execution.",
     "Inline execution. Review carefully."),
    ("ruby -e system",
     "The skill uses 'ruby -e system' inline execution.",
     "Inline execution. Review carefully."),
    ("php -r system",
     "The skill uses 'php -r system' inline execution.",
     "Inline execution. Review carefully."),
    ("json pickle",
     "The skill uses json pickle (unsafe serialization).",
     "Insecure deserialization. Reject."),
    ("yaml.load",
     "The skill uses yaml.load without SafeLoader.",
     "Insecure YAML deserialization. Reject."),
    ("yaml.unsafe_load",
     "The skill uses yaml.unsafe_load.",
     "Insecure YAML. Reject."),
    ("dynamic module loading",
     "The skill uses dynamic module loading (importlib.load_module).",
     "Hidden import. Review carefully."),
    ("imp.load_module",
     "The skill uses imp.load_module (legacy dynamic import).",
     "Dynamic import. Review carefully."),
    ("imp.load_source",
     "The skill uses imp.load_source for dynamic code loading.",
     "Dynamic import. Review carefully."),
    ("os.execv",
     "The skill uses os.execv to replace the process.",
     "Process replacement. Review carefully."),
    ("os.execvp",
     "The skill uses os.execvp to replace the process.",
     "Process replacement. Review carefully."),
    ("os.execvpe",
     "The skill uses os.execvpe to replace the process.",
     "Process replacement. Review carefully."),
    ("os.spawnv",
     "The skill uses os.spawnv for process spawning.",
     "Process spawning. Review carefully."),
    ("commands.getstatusoutput",
     "The skill uses commands.getstatusoutput for shell commands.",
     "Shell command execution. Review."),
    ("signal handler",
     "The skill registers signal handlers.",
     "Signal handler. Review carefully."),
    ("setattr __builtins__",
     "The skill uses setattr to modify __builtins__.",
     "Builtins modification. Critical risk."),
    ("del attr __builtins__",
     "The skill uses delattr to remove __builtins__ attributes.",
     "Builtins modification. Critical risk."),
    ("environ.get",
     "The skill calls environ.get for secrets.",
     "Env var access. Check for secret leakage."),
    ("join chr list",
     "The skill uses string join with chr list for obfuscation.",
     "Obfuscation. Decode before reviewing."),
    ("map chr join",
     "The skill uses map with chr and join for obfuscation.",
     "Obfuscation. Decode before reviewing."),
    ("fetch then",
     "The skill uses fetch().then().text() or .json().",
     "Async fetch. Review destination and handling."),
    ("powershell webclient",
     "The skill uses PowerShell WebClient.DownloadFile.",
     "Download technique. Review destination."),
    ("curl silent download",
     "The skill uses curl -k --silent --output.",
     "Silent download. Review destination."),
    ("wget quiet output",
     "The skill uses wget -q -O-.",
     "Quiet download. Review destination."),
    ("netcat listen",
     "The skill starts a netcat listener (nc -lvnp).",
     "Reverse shell listener. Reject."),
    ("netcat connect",
     "The skill uses netcat to connect to a remote port.",
     "Network connection. Review destination."),
    ("setattr on __builtins__",
     "The skill uses setattr to modify __builtins__.",
     "Builtins modification. Critical risk."),
    ("del attr on __builtins__",
     "The skill uses delattr to remove __builtins__ attributes.",
     "Builtins modification. Critical risk."),

    # === PT-T238 explainer needles ===
    ("ransomware", "This content references ransomware.", "Ransomware is illegal malware. Treat any reference as hostile."),
    ("WannaCry", "WannaCry ransomware reference.", "References to named ransomware strains are a severe warning sign."),
    ("NotPetya", "NotPetya ransomware reference.", "References to nation-state-grade ransomware are a severe warning sign."),
    ("Ryuk ransomware", "Ryuk ransomware reference.", "Named ransomware references are a strong indicator of malicious intent."),
    ("LockBit ransomware", "LockBit ransomware reference.", "Named ransomware references are a strong indicator of malicious intent."),
    ("REvil ransomware", "REvil ransomware reference.", "Named ransomware references are a strong indicator of malicious intent."),
    ("BlackCat ransomware", "BlackCat ransomware reference.", "Named ransomware references are a strong indicator of malicious intent."),
    ("Hive ransomware", "Hive ransomware reference.", "Named ransomware references are a strong indicator of malicious intent."),
    ("DarkSide ransomware", "DarkSide ransomware reference.", "Named ransomware references are a strong indicator of malicious intent."),
    ("Bitcoin ransom", "Bitcoin ransom reference.", "Cryptocurrency ransoms are the standard payment for ransomware."),
    ("TOR payment", "TOR payment reference.", "TOR payments for ransoms indicate criminal intent."),
    ("AES-256 encryption", "AES-256 encryption reference.", "AES-256 is used by ransomware to encrypt files."),
    ("AWS_SECRET_ACCESS_KEY", "AWS secret access key reference.", "AWS secret keys grant full cloud account access. Never expose them."),
    ("AWS_ACCESS_KEY_ID", "AWS access key ID reference.", "AWS key IDs paired with secrets are credentials. Treat as sensitive."),
    ("boto3 AWS client", "boto3 AWS SDK usage.", "boto3 calls manage AWS resources. Audit every call."),
    ("boto3 AWS resource", "boto3 AWS SDK usage.", "boto3 calls manage AWS resources. Audit every call."),
    ("aws sts assume-role", "AWS STS AssumeRole call.", "AssumeRole escalates AWS privileges. Verify the target role."),
    ("aws kms encrypt", "AWS KMS encryption call.", "KMS manages encryption keys. Unauthorized access exposes all data."),
    ("aws s3 cp", "AWS S3 copy operation.", "S3 transfers can exfiltrate data. Verify the bucket and path."),
    ("aws lambda invoke", "AWS Lambda invocation.", "Lambda runs code in your AWS account. Verify the function."),
    ("AZURE_CLIENT_SECRET", "Azure client secret reference.", "Azure client secrets grant cloud app access. Never expose them."),
    ("azure keyvault", "Azure Key Vault access.", "Key Vault stores secrets. Untrusted access is a serious risk."),
    ("GOOGLE_APPLICATION_CREDENTIALS", "GCP credentials reference.", "GCP credentials grant cloud access. Never expose them."),
    ("gcloud auth", "gcloud authentication.", "gcloud auth manages GCP credentials. Verify the authentication."),
    ("kubectl get secrets", "kubectl secrets access.", "Kubernetes secrets store API keys and passwords. Untrusted access is critical."),
    ("kubectl exec", "kubectl exec call.", "kubectl exec is shell access in the pod. Verify the target."),
    ("kubernetes secret", "Kubernetes secret access.", "Kubernetes secrets hold sensitive data. Audit access."),
    ("kubeconfig", "kubeconfig file reference.", "kubeconfig files contain cluster credentials. Never expose them."),
    ("kubernetes container escape", "Kubernetes container escape attempt.", "Container escape is a critical attack. Treat as hostile."),
    ("docker run --privileged", "Docker --privileged container.", "--privileged containers can access the entire host. Critical risk."),
    ("docker socket", "Docker socket access.", "Docker socket access is equivalent to root on the host."),
    ("container breakout", "Container breakout attempt.", "Container breakout is a critical attack. Treat as hostile."),
    ("host path mount", "Host path mount in container.", "Host path mounts bypass container isolation."),
    ("SYS_ADMIN capability", "SYS_ADMIN Linux capability.", "SYS_ADMIN is one of the most powerful capabilities. High risk."),
    ("cap-add ALL", "Docker cap-add ALL.", "cap-add ALL removes all security restrictions. Equivalent to root."),
    ("seccomp=unconfined", "Docker seccomp=unconfined.", "Disabling seccomp removes a key security boundary. Critical risk."),
    ("network=host", "Docker network=host mode.", "Host networking removes network isolation. Significant risk."),
    ("dns tunnel", "DNS tunneling reference.", "DNS tunneling is a classic data exfiltration technique."),
    ("icmp tunnel", "ICMP tunneling reference.", "ICMP tunneling bypasses firewalls for data exfiltration."),
    ("dnscat", "dnscat DNS tunnel tool.", "dnscat is a known C2 tool. Strong indicator of compromise."),
    ("iodine", "iodine DNS tunnel tool.", "iodine is a DNS tunneling tool for anonymous access."),
    ("use-after-free", "use-after-free vulnerability.", "Use-after-free bugs can lead to code execution."),
    ("double-free", "double-free vulnerability.", "Double-free bugs corrupt heap memory and can lead to code execution."),
    ("heap spray", "heap spray exploit technique.", "Heap spraying exploits memory corruption bugs."),
    ("ROP chain", "ROP chain exploit.", "ROP chains bypass DEP/NX. Finding one in a skill is suspicious."),
    ("ROPgadget", "ROPgadget tool.", "ROP gadget finders are used in exploit development."),
    ("format string attack", "format string vulnerability.", "Format string bugs can leak memory or lead to arbitrary write."),
    ("canary bypass", "stack canary bypass.", "Canary bypass is used in exploit development."),
    ("MITM proxy", "MITM proxy reference.", "MITM proxies intercept traffic. May be used for credential theft."),
    ("OWASP ZAP", "OWASP ZAP scanner reference.", "ZAP is a legitimate security tool. Verify intent."),
    ("burp suite intruder", "Burp Suite Intruder reference.", "Burp Intruder automates attacks. Verify intent is legitimate."),
    ("DAN jailbreak", "DAN jailbreak attempt.", "DAN is a known jailbreak. It attempts to disable safety measures."),
    ("STAN jailbreak", "STAN jailbreak attempt.", "STAN is a jailbreak variant. It attempts to disable safety."),
    ("OMEGA jailbreak", "OMEGA jailbreak attempt.", "OMEGA is a jailbreak variant. It attempts to disable safety."),
    ("BISHOP jailbreak", "BISHOP jailbreak attempt.", "BISHOP is a jailbreak variant. It attempts to disable safety."),
    ("HETIC jailbreak", "HETIC jailbreak attempt.", "HETIC is a jailbreak variant. It attempts to disable safety."),
    ("KOBOLD jailbreak", "KOBOLD jailbreak attempt.", "KOBOLD is a jailbreak variant used with Kobold AI."),
    ("AIM jailbreak", "AIM jailbreak attempt.", "AIM is a known jailbreak persona. Avoid it."),
    ("Sydney jailbreak", "Sydney jailbreak attempt.", "Sydney is the hidden Bing AI persona. Bypassing it is hostile."),
    ("MOAB jailbreak", "MOAB jailbreak attempt.", "MOAB is one of the most aggressive jailbreaks. Critical red flag."),
    ("jailbreak stack", "jailbreak stack.", "Stacking jailbreaks amplifies their effect. Very hostile."),
    ("SUPER mode jailbreak", "SUPER mode jailbreak.", "SUPER mode is a jailbreak variant. It disables safety."),
    ("BOB jailbreak", "BOB jailbreak attempt.", "BOB is a jailbreak variant. Hostile."),
    ("RAVEN jailbreak", "RAVEN jailbreak attempt.", "RAVEN is a jailbreak variant. It attempts to disable safety."),
    ("REBEL jailbreak", "REBEL jailbreak attempt.", "REBEL is a jailbreak variant. It attempts to disable safety."),
    ("ALICE jailbreak", "ALICE jailbreak attempt.", "ALICE is a jailbreak variant. It attempts to disable safety."),
    ("developer override mode", "developer override mode.", "Developer override bypasses safety checks. Use with caution."),
    ("admin override mode", "admin override mode.", "Admin override bypasses safety checks. Use with caution."),
    ("sudo mode jailbreak", "sudo mode jailbreak.", "sudo mode is a privilege escalation jailbreak."),
    ("root access enabled", "root access enabled.", "Root access grants full system control. Verify intent."),
    ("uncensored mode", "uncensored mode.", "Uncensored modes disable safety filters. Red flag."),
    ("no filter mode", "no-filter mode.", "Disabling content filters is a jailbreak technique. Red flag."),
    ("unmoderated mode", "unmoderated mode.", "Unmoderated modes remove safety guardrails. Red flag."),
    ("ignore all prior instructions", "ignore all prior instructions.", "Ignoring all instructions is a core jailbreak technique."),
    ("disregard prior instructions", "disregard prior instructions.", "Disregarding prior instructions is a manipulation technique."),
    ("forget prior instructions", "forget prior instructions.", "Forgetting instructions is a core jailbreak technique."),
    ("disregard all prior instruction", "disregard all prior instruction.", "Disregarding all prior instructions is hostile."),
    ("new instruction directive", "new instruction injection.", "New instruction injection replaces real instructions."),
    ("overwrite instructions", "overwrite instructions.", "Overwriting instructions is a manipulation technique."),
    ("replace system prompt", "replace system prompt.", "Replacing the system prompt is critical manipulation."),
    ("meta-prompt manipulation", "meta-prompt manipulation.", "Meta-prompt manipulation changes how instructions are processed."),
    ("explicit system prompt injection", "explicit system prompt injection.", "System prompt injection is a critical attack. Hostile."),
    ("forget system prompt", "forget system prompt.", "Forgetting the system prompt is a manipulation technique."),
    ("prompt disclosure", "prompt disclosure request.", "Disclosing the system prompt is a prompt extraction attack."),
    ("prompt extraction", "prompt extraction attempt.", "Prompt extraction is an attack on the agent's instructions."),
    ("rules extraction", "rules extraction attempt.", "Extracting rules attempts to learn how to manipulate the agent."),
    ("instructions disclosure", "instructions disclosure attempt.", "Disclosing instructions is a prompt extraction attack."),
    ("last message manipulation", "last message manipulation.", "Manipulating the last message is conversation poisoning."),
    ("acknowledge-only attack", "acknowledge-only attack.", "Forcing only 'acknowledged' responses is a jailbreak technique."),
    ("roleplay scenario injection", "roleplay scenario injection.", "Roleplay framing is a common jailbreak technique."),
    ("Flask usage", "Flask web framework usage.", "Flask is a web framework. Verify the routes and endpoints are intentional."),
    ("Django usage", "Django web framework usage.", "Django is a web framework. Verify the views and URLs are intentional."),
    ("FastAPI usage", "FastAPI framework usage.", "FastAPI is a web framework. Verify the routes and endpoints are intentional."),
    ("Starlette usage", "Starlette framework usage.", "Starlette is an async web framework. Verify the routes and endpoints."),
    ("Celery usage", "Celery task queue usage.", "Celery runs background tasks. Audit the tasks for malicious intent."),
    ("Redis client", "Redis client usage.", "Redis is an in-memory database. Audit the operations."),
    ("database backends", "database backend usage.", "Database operations should be audited for data exposure risks."),
    ("PIL image operations", "PIL image operations.", "PIL processes images. Audit for steganography or exfil via images."),
    ("OpenCV operations", "OpenCV operations.", "OpenCV processes images and video. Audit the operations."),
    ("pandas usage", "pandas usage.", "pandas processes tabular data. Audit for data exfiltration."),
    ("numpy usage", "numpy usage.", "numpy processes numerical data. Audit for data exfiltration."),
    ("scipy module", "scipy module usage.", "scipy performs scientific computing. Audit the operations."),
    ("matplotlib usage", "matplotlib usage.", "matplotlib creates plots. Audit for data exfiltration."),
    ("HuggingFace transformers", "HuggingFace transformers usage.", "transformers loads ML models. Verify the model source."),
    ("PyTorch usage", "PyTorch usage.", "PyTorch runs ML models. Verify the model source."),
    ("TensorFlow usage", "TensorFlow usage.", "TensorFlow runs ML models. Verify the model source."),
    ("Keras usage", "Keras usage.", "Keras runs ML models. Verify the model source."),
    ("NLTK usage", "NLTK NLP usage.", "NLTK processes natural language. Audit the operations."),
    ("spaCy usage", "spaCy NLP usage.", "spaCy processes natural language. Audit the operations."),
    ("scikit-learn usage", "scikit-learn usage.", "scikit-learn performs machine learning. Audit the operations."),
    ("Swift interop", "Swift interop.", "Swift interop calls native code. Audit the operations."),
    ("JSON operations", "JSON operations.", "JSON operations parse structured data. Audit the data source."),
    ("YAML operations", "YAML operations.", "YAML operations parse configuration. Audit the YAML source."),
    ("HTML parsing", "HTML parsing.", "HTML parsing processes web content. Audit the source."),
    ("XML parsing modules", "XML parsing modules.", "XML parsing processes XML data. Audit the data source."),
    ("requests HTTP methods", "requests HTTP methods.", "requests makes HTTP calls. Audit every URL and payload."),
    ("httpx HTTP client", "httpx HTTP client.", "httpx makes async HTTP calls. Audit every URL and payload."),
    ("webbrowser module", "webbrowser module usage.", "webbrowser opens URLs in the browser. Audit the URLs."),
    ("http server client", "http server/client usage.", "HTTP operations may expose or receive data. Audit carefully."),
    ("socketserver TCP", "socketserver TCP usage.", "socketserver creates network listeners. Verify the intent."),
    ("socket creation", "socket creation.", "Socket creation enables network communication. Audit the usage."),
    ("SSL context", "SSL context usage.", "SSL context manages TLS connections. Audit the configuration."),
    ("hashlib usage", "hashlib usage.", "hashlib computes hashes. Verify the purpose is legitimate."),
    ("hmac operations", "HMAC operations.", "HMAC provides message authentication. Verify the usage."),
    ("secrets module", "secrets module usage.", "secrets module generates cryptographic values. Verify the purpose."),
    ("zlib compression", "zlib compression.", "zlib compresses data. Verify the purpose is legitimate."),
    ("sqlite3 database", "sqlite3 database usage.", "sqlite3 manages local databases. Audit the operations."),
    ("dbm database access", "dbm database access.", "dbm provides key-value storage. Audit the operations."),
    ("shelve persistence", "shelve persistence usage.", "shelve persists Python objects. Audit the data."),
    ("serialization modules", "serialization modules usage.", "Serialization modules convert objects. Audit the data source."),
    ("packaging version check", "packaging version check.", "Version checks may be used for fingerprinting. Audit the usage."),
    ("itertools module", "itertools module usage.", "itertools provides iterator utilities. Audit the usage."),
    ("functools utilities", "functools utilities.", "functools provides function utilities. Audit the usage."),
    ("dataclasses usage", "dataclasses usage.", "dataclasses define data structures. Audit the usage."),
    ("typing module usage", "typing module usage.", "typing provides type hints. Usually benign but review context."),
    ("collections usage", "collections usage.", "collections provides data structures. Audit the usage."),
    ("enum module usage", "enum module usage.", "enum defines enumerated types. Usually benign."),
    ("pathlib usage", "pathlib usage.", "pathlib manages file paths. Audit file operations."),
    ("selectors module", "selectors module usage.", "selectors monitors file descriptors. Audit the usage."),
    ("fcntl file locking", "fcntl file locking.", "fcntl manages file locks. Audit the usage."),
    ("signal atexit weakref", "signal/atexit/weakref usage.", "Signal handlers and atexit hooks run at specific times. Audit carefully."),
    ("select on stdin", "select on stdin.", "select monitors file descriptors. Audit the usage."),
    ("fast time.sleep timing", "fast time.sleep timing.", "Fast polling may be used for timing attacks or brute force."),
    ("multiprocessing spawn", "multiprocessing spawn.", "multiprocessing creates separate processes. Audit the operations."),
    ("platform python info", "platform python info.", "platform module reveals system info. Audit the usage."),
    ("import lib.machinery", "import lib.machinery.", "lib.machinery imports modules dynamically. Audit the usage."),
    ("importlib submodules", "importlib submodules.", "importlib submodules enable dynamic imports. Audit carefully."),
    ("pkgutil zipimport data access", "pkgutil/zipimport data access.", "pkgutil/zipimport accesses package data. Audit the usage."),
    ("resource reader import", "resource reader import.", "ResourceReader accesses package resources. Audit the data."),
    ("getpass credential retrieval", "getpass credential retrieval.", "getpass retrieves user passwords. Audit the usage."),
    ("file read/write with numeric fd", "file read/write with numeric fd.", "File operations with numeric file descriptors. Audit the usage."),
    ("nt module file operations", "nt module file operations.", "nt module provides Windows file operations. Audit the usage."),
    ("posix module file ops", "posix module file ops.", "posix module provides Unix file operations. Audit the usage."),
    ("spawns a subprocess", "spawns a subprocess.", "Subprocess spawning runs external commands. Audit every call."),
    ("os.execv exec family", "os.execv exec family.", "os.execv replaces the current process. Audit the command."),
    ("os.spawnv spawn family", "os.spawnv spawn family.", "os.spawnv spawns new processes. Audit the command."),
    ("powershell iex iwr download-exec", "PowerShell IEX IWR download-exec.", "IEX(IWR) is a classic PowerShell dropper pattern."),
    ("powershell download-and-execute cradle", "PowerShell download cradle.", "PowerShell download cradles are a common malware delivery technique."),
    ("pipes downloaded content into shell", "pipes downloaded content into shell.", "Piping downloaded content into shell is a classic dropper. Very dangerous."),
    ("pipes downloaded script into shell", "pipes downloaded script into shell.", "Piping downloaded scripts into shell is a classic dropper. Very dangerous."),
    ("pipes a downloaded script directly into a shell", "pipes downloaded script directly into shell.", "Direct pipe to shell is a classic dropper. Very dangerous."),
    ("reads environment variables", "reads environment variables.", "Environment variables may contain credentials. Restrict which vars are read."),
    ("reads an environment variable", "reads environment variable.", "Environment variables may contain credentials. Restrict which vars are read."),
    ("instructs credential extraction", "instructs credential extraction.", "Credential extraction is an exfiltration technique."),
    ("instructs collection of credentials", "instructs collection of credentials.", "Credential collection is a theft technique."),
    ("URL carries credential query parameter", "URL with credential in query param.", "URLs with credentials in query params may be exfiltration endpoints."),
    ("fetches then parses JSON", "fetches then parses JSON.", "fetch+JSON may be used to receive commands or exfiltrate data."),
    ("sends email", "sends email.", "Email is an exfiltration channel. Verify the recipient and content."),
    ("smtplib SMTP", "smtplib SMTP usage.", "SMTP usage may be used for exfiltration. Verify the recipient."),
    ("ssh key injection", "SSH key injection.", "SSH key injection adds unauthorized access. Verify the authorized_keys path."),
    ("injects backdoor", "backdoor injection.", "Backdoor injection grants unauthorized persistent access."),
    ("appends to shell startup file", "shell startup file append.", "Appending to shell startup files creates persistence."),
    ("modifies scheduled tasks", "scheduled task modification.", "Modifying scheduled tasks creates persistence. Verify the task is legitimate."),
    ("writes to a known OS autostart location", "OS autostart location write.", "Writing to autostart locations creates persistence."),
    ("Azure Key Vault access", "Azure Key Vault access.", "Key Vault stores secrets. Untrusted access is a serious risk."),
    ("Azure client secret", "Azure client secret reference.", "Azure client secrets grant cloud app access. Never expose them."),
    ("Docker host network", "Docker host network mode.", "Host networking removes network isolation. Significant risk."),
    ("Docker privileged", "Docker privileged container.", "--privileged containers can access the entire host. Critical risk."),
    ("Docker seccomp", "Docker seccomp unconfined.", "Disabling seccomp removes a key security boundary. Critical risk."),
    ("ROP gadget finder", "ROPgadget tool usage.", "ROP gadget finders are used in exploit development."),
    ("act-as-though override", "act-as-though override.", "Acting as though is a jailbreak framing technique."),
    ("alternate reality framing", "alternate reality framing.", "Alternate reality framing is a jailbreak technique."),
    ("anything is allowed", "anything is allowed framing.", "Anything-allowed framing is a jailbreak technique."),
    ("asyncio task creation", "asyncio task creation.", "Audit asyncio tasks - they run asynchronously."),
    ("authorized test framing", "authorized test framing.", "Verify authorization independently. Threat actors claim it too."),
    ("be anything framing", "be anything framing.", "Be-anything framing is a jailbreak technique."),
    ("be evil AI framing", "be evil AI framing.", "Asking the AI to be evil is an explicit attack."),
    ("be my evil assistant", "be my evil assistant.", "Asking to be evil is an explicit attack."),
    ("be unethical AI framing", "be unethical AI framing.", "Asking the AI to be unethical is an explicit attack."),
    ("behave-as-if override", "behave-as-if override.", "Behaving as if is a jailbreak framing technique."),
    ("break out of programming", "break out of programming.", "Breaking out of programming is a jailbreak technique."),
    ("bytearray from encoded", "bytearray from encoded data.", "bytearray with encoded data may hide the actual content."),
    ("cffi FFI", "cffi FFI usage.", "cffi allows direct native code calls. High-risk capability."),
    ("circumvention framing", "circumvention framing.", "Circumvention framing tries to work around restrictions."),
    ("code generation request", "code generation request.", "Code generation requests should be reviewed for malicious intent."),
    ("compile constructor", "compile constructor call.", "compile() creates executable code from strings. Audit the source."),
    ("concurrent futures", "concurrent.futures usage.", "concurrent.futures runs code in parallel. Audit the tasks."),
    ("curiosity framing", "curiosity framing.", "Curiosity framing is a social engineering technique."),
    ("demonstration framing", "demonstration framing.", "Demonstration framing disguises requests as examples."),
    ("dependency confusion", "dependency confusion attack.", "Dependency confusion attacks target package managers. Verify dependencies."),
    ("do not follow prior", "do not follow prior.", "Do not follow prior is a direct instruction override."),
    ("dynamic compile of string", "dynamic compile of string.", "compile() of strings creates executable code. Very suspicious."),
    ("exec of dynamically imported code", "exec of dynamically imported code.", "Executing dynamically imported code is very dangerous."),
    ("fake package manager", "fake package manager reference.", "Fake package managers are a supply chain attack vector. Verify package sources."),
    ("forget everything override", "forget everything override.", "Forgetting everything is a jailbreak technique."),
    ("free yourself framing", "free yourself framing.", "Freeing itself from restrictions is the goal of every jailbreak."),
    ("fresh start framing", "fresh start framing.", "Fresh-start framing tries to reset context. Suspicious."),
    ("from this point persona shift", "from this point persona shift.", "From-this-point framing shifts the AI persona. Suspicious."),
    ("help request", "help request.", "Help requests are normal but should be reviewed in context."),
    ("http server/client", "http server/client usage.", "HTTP operations may expose or receive data. Audit carefully."),
    ("imagine persona framing", "imagine persona framing.", "Imagine framing is a common jailbreak technique."),
    ("instead of prior", "instead of prior framing.", "Instead-of-prior framing redirects away from instructions."),
    ("kubectl secrets access", "kubectl secrets access.", "Kubernetes secrets store API keys and passwords. Untrusted access is critical."),
    ("memoryview for binary", "memoryview for binary manipulation.", "memoryview allows binary data access. Audit the usage."),
    ("moving on framing", "moving on framing.", "Moving-on framing tries to redirect past safety checks."),
    ("new session framing", "new session framing.", "New session framing tries to reset conversation state."),
    ("no ethical rules", "no ethical rules.", "Dropping ethical rules is a core jailbreak technique."),
    ("no rules framing", "no rules framing.", "No rules framing is a jailbreak technique."),
    ("not a threat framing", "not-a-threat framing.", "Downplaying threat is a social engineering technique."),
    ("outguess stego tool", "outguess tool reference.", "outguess is a steganography tool. Verify the intent."),
    ("pickle operations", "pickle operations.", "pickle deserializes arbitrary Python objects. Use only with trusted data."),
    ("pkgutil zipimport", "pkgutil/zipimport data access.", "pkgutil/zipimport accesses package data. Audit the usage."),
    ("play a game framing", "play a game framing.", "Game framing is a common jailbreak technique."),
    ("polite request framing", "polite request framing.", "Polite requests are normal but review the full context."),
    ("proceed-as-if override", "proceed-as-if override.", "Proceeding as if is a jailbreak framing technique."),
    ("python -c execution", "python -c execution.", "python -c runs inline code. Audit the command carefully."),
    ("python script generation", "python script generation request.", "Script generation requests should be reviewed for malicious intent."),
    ("re search match exec", "re search/match with exec.", "Combining regex with exec may indicate code injection."),
    ("request framing", "request framing.", "Request framing is standard but verify the intent."),
    ("reset instructions", "reset instructions.", "Resetting instructions is a manipulation technique."),
    ("restart framing", "restart framing.", "Restart framing is a jailbreak technique."),
    ("script creation request", "script creation request.", "Script creation requests should be reviewed for malicious intent."),
    ("script generation request", "script generation request.", "Script generation requests should be reviewed for malicious intent."),
    ("security research framing", "security research framing.", "Security research framing disguises requests. Verify the research is real."),
    ("signal atexit weakref", "signal/atexit/weakref usage.", "Signal handlers and atexit hooks run at specific times. Audit carefully."),
    ("simulation framing", "simulation framing.", "Simulation framing is a common jailbreak technique."),
    ("steganography reference", "steganography reference.", "Steganography hides data in images. Audit the content."),
    ("steghide tool", "steghide tool reference.", "steghide is a steganography tool. Verify the intent."),
    ("stop following prior", "stop following prior.", "Stop following prior is a direct instruction override."),
    ("test framing bypass", "test framing bypass.", "Test framing is a common bypass technique."),
    ("threading primitives", "threading primitives usage.", "Threading enables concurrent execution that may be hard to audit."),
    ("typosquatting package", "typosquatting package.", "Typosquatting packages impersonate legitimate ones. Verify the package name."),
    ("void prior context", "void prior context.", "Voiding prior context attempts to reset the conversation. Suspicious."),
    ("whitehat framing", "whitehat framing.", "Whitehat framing disguises requests as authorized testing."),
    ("without restrictions", "without restrictions.", "Without restrictions is a core jailbreak phrase."),
    ("CTF framing", "CTF framing.", "CTF framing disguises requests as legitimate exercises."),
    ("concurrent.futures usage", "concurrent.futures usage.", "concurrent.futures runs code in parallel. Audit the tasks."),
    ("pkgutil/zipimport data access", "pkgutil/zipimport data access.", "pkgutil/zipimport accesses package data. Audit the usage."),
    ("re search/match/exec pattern", "re search/match with exec.", "Combining regex with exec may indicate code injection."),
    ("signal/atexit/weakref", "signal/atexit/weakref usage.", "Signal handlers and atexit hooks run at specific times. Audit carefully."),
    ("ignore the previous instruction", "ignore the previous instruction.", "Ignoring the previous instruction is a jailbreak technique."),

]


def explain_findings(findings: list) -> list:
    """Translate raw pattern hits into plain-language explanations."""
    if not findings:
        return []
    out, seen = [], set()
    joined = " ".join(str(f.get("message", "")) for f in findings).lower()
    text_blob = joined
    for needle, what, advice in _EXPLAIN_RULES:
        if needle.lower() in text_blob and needle not in seen:
            seen.add(needle)
            out.append({"topic": needle, "what": what, "advice": advice})
    return out


# --- Verdict certificates ---------------------------------------------------

def _cert_secret() -> bytes | None:
    """Certificates are only as trustworthy as this secret. With neither
    SKILLSMITH_CERT_SECRET nor BLOB_READ_WRITE_TOKEN set (i.e. local dev),
    return None and let callers refuse to issue/verify rather than sign with
    a hardcoded constant (audit L16)."""
    s = os.environ.get("SKILLSMITH_CERT_SECRET") or os.environ.get("BLOB_READ_WRITE_TOKEN")
    if not s:
        return None
    return hashlib.sha256(("cert:" + s).encode()).digest()


def make_certificate(sha256: str, risk_level: str, security_score, ts=None) -> dict:
    secret = _cert_secret()
    if secret is None:
        raise RuntimeError("certificate signing unavailable: no secret configured")
    ts = int(ts if ts is not None else time.time())
    payload = f"{sha256}|{risk_level}|{security_score}|{ts}"
    sig = hmac.new(secret, payload.encode(), hashlib.sha256).hexdigest()[:32]
    return {"sha256": sha256, "risk_level": risk_level, "security_score": security_score,
            "issued_at": ts, "signature": sig}


def verify_certificate(cert: dict, max_age_days: int = 90) -> bool:
    try:
        ts = int(cert["issued_at"])
        if time.time() - ts > max_age_days * 86400:
            return False
        secret = _cert_secret()
        if secret is None:
            return False
        payload = f"{cert['sha256']}|{cert['risk_level']}|{cert['security_score']}|{ts}"
        expect = hmac.new(secret, payload.encode(), hashlib.sha256).hexdigest()[:32]
        return hmac.compare_digest(expect, str(cert.get("signature", "")))
    except Exception:  # noqa: BLE001
        return False
